### ISSUE TITLE
NPE while creating test client

### ISSUE THREAD

**Issue by axandar** [GluuFederation/scim#6]
When registering test client, api returns 0 in `client_secret_expires_at`.
If `client_secret_expires_at` is 0, then `RegisterResponse` object is created with variable clientSecretExpiresAt as null.
At `TestModeScimsClient#triggerRegistrationIfNeeded` `clientExpiration` variable is set to `response.getClientSecretExpiresAt().getTime()` and gives NullPointerException. 

Simple null check will create new registration request on every program run.
Maybe provide option to provide OpenID client details via constructor?

**Comment by nynymike** [comment]
Good find. @jgomer2001 can check it out.

**Comment by jgomer2001** [comment]
Good catch @axandar . Formerly clients always had an expiration date in Gluu, so `getClientSecretExpiresAt()` never returned null. I adjusted to conform. 

Likewise I added a new factory method so that developers can pass client ID/secret to avoid multiple registrations when testing.

Docs were [updated](https://github.com/GluuFederation/docs-gluu-server-prod/commit/0d7b9cf1f058914c1ae8fbc24b30653538553ea7) in this regard.

Changes will be present in upcoming 4.2.1, meanwhile you can point to snapshot artifact:

```
<dependency>
  <groupId>org.gluu</groupId>
  <artifactId>scim-client</artifactId>
  <version>4.2.1-SNAPSHOT</version>
</dependency>
```

**Comment by jgomer2001** [comment]
Closing this. You can now use version `4.2.1.Final`
